<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Workspace;
use App\Models\WorkspaceUser;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $country_list = array(
            array("name" => "Afghanistan","code" => "AF","alpha_3" => "AFG"),
            array("name" => "Aland Islands","code" => "AX","alpha_3" => "ALA"),
            array("name" => "Albania","code" => "AL","alpha_3" => "ALB"),
            array("name" => "Algeria","code" => "DZ","alpha_3" => "DZA"),
            array("name" => "American Samoa","code" => "AS","alpha_3" => "ASM"),
            array("name" => "Andorra","code" => "AD","alpha_3" => "AND"),
            array("name" => "Angola","code" => "AO","alpha_3" => "AGO"),
            array("name" => "Anguilla","code" => "AI","alpha_3" => "AIA"),
            array("name" => "Antarctica","code" => "AQ","alpha_3" => "ATA"),
            array("name" => "Antigua and Barbuda","code" => "AG","alpha_3" => "ATG"),
            array("name" => "Argentina","code" => "AR","alpha_3" => "ARG"),
            array("name" => "Armenia","code" => "AM","alpha_3" => "ARM"),
            array("name" => "Aruba","code" => "AW","alpha_3" => "ABW"),
            array("name" => "Australia","code" => "AU","alpha_3" => "AUS"),
            array("name" => "Austria","code" => "AT","alpha_3" => "AUT"),
            array("name" => "Azerbaijan","code" => "AZ","alpha_3" => "AZE"),
            array("name" => "Bahamas","code" => "BS","alpha_3" => "BHS"),
            array("name" => "Bahrain","code" => "BH","alpha_3" => "BHR"),
            array("name" => "Bangladesh","code" => "BD","alpha_3" => "BGD"),
            array("name" => "Barbados","code" => "BB","alpha_3" => "BRB"),
            array("name" => "Belarus","code" => "BY","alpha_3" => "BLR"),
            array("name" => "Belgium","code" => "BE","alpha_3" => "BEL"),
            array("name" => "Belize","code" => "BZ","alpha_3" => "BLZ"),
            array("name" => "Benin","code" => "BJ","alpha_3" => "BEN"),
            array("name" => "Bermuda","code" => "BM","alpha_3" => "BMU"),
            array("name" => "Bhutan","code" => "BT","alpha_3" => "BTN"),
            array("name" => "Bolivia","code" => "BO","alpha_3" => "BOL"),
            array("name" => "Bonaire, Sint Eustatius and Saba","code" => "BQ","alpha_3" => "BES"),
            array("name" => "Bosnia and Herzegovina","code" => "BA","alpha_3" => "BIH"),
            array("name" => "Botswana","code" => "BW","alpha_3" => "BWA"),
            array("name" => "Bouvet Island","code" => "BV","alpha_3" => "BVT"),
            array("name" => "Brazil","code" => "BR","alpha_3" => "BRA"),
            array("name" => "British Indian Ocean Territory","code" => "IO","alpha_3" => "IOT"),
            array("name" => "Brunei Darussalam","code" => "BN","alpha_3" => "BRN"),
            array("name" => "Bulgaria","code" => "BG","alpha_3" => "BGR"),
            array("name" => "Burkina Faso","code" => "BF","alpha_3" => "BFA"),
            array("name" => "Burundi","code" => "BI","alpha_3" => "BDI"),
            array("name" => "Cambodia","code" => "KH","alpha_3" => "KHM"),
            array("name" => "Cameroon","code" => "CM","alpha_3" => "CMR"),
            array("name" => "Canada","code" => "CA","alpha_3" => "CAN"),
            array("name" => "Cape Verde","code" => "CV","alpha_3" => "CPV"),
            array("name" => "Cayman Islands","code" => "KY","alpha_3" => "CYM"),
            array("name" => "Central African Republic","code" => "CF","alpha_3" => "CAF"),
            array("name" => "Chad","code" => "TD","alpha_3" => "TCD"),
            array("name" => "Chile","code" => "CL","alpha_3" => "CHL"),
            array("name" => "China","code" => "CN","alpha_3" => "CHN"),
            array("name" => "Christmas Island","code" => "CX","alpha_3" => "CXR"),
            array("name" => "Cocos (Keeling) Islands","code" => "CC","alpha_3" => "CCK"),
            array("name" => "Colombia","code" => "CO","alpha_3" => "COL"),
            array("name" => "Comoros","code" => "KM","alpha_3" => "COM"),
            array("name" => "Congo","code" => "CG","alpha_3" => "COG"),
            array("name" => "Congo, Democratic Republic of the Congo","code" => "CD","alpha_3" => "COD"),
            array("name" => "Cook Islands","code" => "CK","alpha_3" => "COK"),
            array("name" => "Costa Rica","code" => "CR","alpha_3" => "CRI"),
            array("name" => "Cote D'Ivoire","code" => "CI","alpha_3" => "CIV"),
            array("name" => "Croatia","code" => "HR","alpha_3" => "HRV"),
            array("name" => "Cuba","code" => "CU","alpha_3" => "CUB"),
            array("name" => "Curacao","code" => "CW","alpha_3" => "CUW"),
            array("name" => "Cyprus","code" => "CY","alpha_3" => "CYP"),
            array("name" => "Czech Republic","code" => "CZ","alpha_3" => "CZE"),
            array("name" => "Denmark","code" => "DK","alpha_3" => "DNK"),
            array("name" => "Djibouti","code" => "DJ","alpha_3" => "DJI"),
            array("name" => "Dominica","code" => "DM","alpha_3" => "DMA"),
            array("name" => "Dominican Republic","code" => "DO","alpha_3" => "DOM"),
            array("name" => "Ecuador","code" => "EC","alpha_3" => "ECU"),
            array("name" => "Egypt","code" => "EG","alpha_3" => "EGY"),
            array("name" => "El Salvador","code" => "SV","alpha_3" => "SLV"),
            array("name" => "Equatorial Guinea","code" => "GQ","alpha_3" => "GNQ"),
            array("name" => "Eritrea","code" => "ER","alpha_3" => "ERI"),
            array("name" => "Estonia","code" => "EE","alpha_3" => "EST"),
            array("name" => "Ethiopia","code" => "ET","alpha_3" => "ETH"),
            array("name" => "Falkland Islands (Malvinas)","code" => "FK","alpha_3" => "FLK"),
            array("name" => "Faroe Islands","code" => "FO","alpha_3" => "FRO"),
            array("name" => "Fiji","code" => "FJ","alpha_3" => "FJI"),
            array("name" => "Finland","code" => "FI","alpha_3" => "FIN"),
            array("name" => "France","code" => "FR","alpha_3" => "FRA"),
            array("name" => "French Guiana","code" => "GF","alpha_3" => "GUF"),
            array("name" => "French Polynesia","code" => "PF","alpha_3" => "PYF"),
            array("name" => "French Southern Territories","code" => "TF","alpha_3" => "ATF"),
            array("name" => "Gabon","code" => "GA","alpha_3" => "GAB"),
            array("name" => "Gambia","code" => "GM","alpha_3" => "GMB"),
            array("name" => "Georgia","code" => "GE","alpha_3" => "GEO"),
            array("name" => "Germany","code" => "DE","alpha_3" => "DEU"),
            array("name" => "Ghana","code" => "GH","alpha_3" => "GHA"),
            array("name" => "Gibraltar","code" => "GI","alpha_3" => "GIB"),
            array("name" => "Greece","code" => "GR","alpha_3" => "GRC"),
            array("name" => "Greenland","code" => "GL","alpha_3" => "GRL"),
            array("name" => "Grenada","code" => "GD","alpha_3" => "GRD"),
            array("name" => "Guadeloupe","code" => "GP","alpha_3" => "GLP"),
            array("name" => "Guam","code" => "GU","alpha_3" => "GUM"),
            array("name" => "Guatemala","code" => "GT","alpha_3" => "GTM"),
            array("name" => "Guernsey","code" => "GG","alpha_3" => "GGY"),
            array("name" => "Guinea","code" => "GN","alpha_3" => "GIN"),
            array("name" => "Guinea-Bissau","code" => "GW","alpha_3" => "GNB"),
            array("name" => "Guyana","code" => "GY","alpha_3" => "GUY"),
            array("name" => "Haiti","code" => "HT","alpha_3" => "HTI"),
            array("name" => "Heard Island and McDonald Islands","code" => "HM","alpha_3" => "HMD"),
            array("name" => "Holy See (Vatican City State)","code" => "VA","alpha_3" => "VAT"),
            array("name" => "Honduras","code" => "HN","alpha_3" => "HND"),
            array("name" => "Hong Kong","code" => "HK","alpha_3" => "HKG"),
            array("name" => "Hungary","code" => "HU","alpha_3" => "HUN"),
            array("name" => "Iceland","code" => "IS","alpha_3" => "ISL"),
            array("name" => "India","code" => "IN","alpha_3" => "IND"),
            array("name" => "Indonesia","code" => "ID","alpha_3" => "IDN"),
            array("name" => "Iran, Islamic Republic of","code" => "IR","alpha_3" => "IRN"),
            array("name" => "Iraq","code" => "IQ","alpha_3" => "IRQ"),
            array("name" => "Ireland","code" => "IE","alpha_3" => "IRL"),
            array("name" => "Isle of Man","code" => "IM","alpha_3" => "IMN"),
            array("name" => "Israel","code" => "IL","alpha_3" => "ISR"),
            array("name" => "Italy","code" => "IT","alpha_3" => "ITA"),
            array("name" => "Jamaica","code" => "JM","alpha_3" => "JAM"),
            array("name" => "Japan","code" => "JP","alpha_3" => "JPN"),
            array("name" => "Jersey","code" => "JE","alpha_3" => "JEY"),
            array("name" => "Jordan","code" => "JO","alpha_3" => "JOR"),
            array("name" => "Kazakhstan","code" => "KZ","alpha_3" => "KAZ"),
            array("name" => "Kenya","code" => "KE","alpha_3" => "KEN"),
            array("name" => "Kiribati","code" => "KI","alpha_3" => "KIR"),
            array("name" => "Korea, Democratic People's Republic of","code" => "KP","alpha_3" => "PRK"),
            array("name" => "Korea, Republic of","code" => "KR","alpha_3" => "KOR"),
            array("name" => "Kosovo","code" => "XK","alpha_3" => "XKX"),
            array("name" => "Kuwait","code" => "KW","alpha_3" => "KWT"),
            array("name" => "Kyrgyzstan","code" => "KG","alpha_3" => "KGZ"),
            array("name" => "Lao People's Democratic Republic","code" => "LA","alpha_3" => "LAO"),
            array("name" => "Latvia","code" => "LV","alpha_3" => "LVA"),
            array("name" => "Lebanon","code" => "LB","alpha_3" => "LBN"),
            array("name" => "Lesotho","code" => "LS","alpha_3" => "LSO"),
            array("name" => "Liberia","code" => "LR","alpha_3" => "LBR"),
            array("name" => "Libyan Arab Jamahiriya","code" => "LY","alpha_3" => "LBY"),
            array("name" => "Liechtenstein","code" => "LI","alpha_3" => "LIE"),
            array("name" => "Lithuania","code" => "LT","alpha_3" => "LTU"),
            array("name" => "Luxembourg","code" => "LU","alpha_3" => "LUX"),
            array("name" => "Macao","code" => "MO","alpha_3" => "MAC"),
            array("name" => "Macedonia, the Former Yugoslav Republic of","code" => "MK","alpha_3" => "MKD"),
            array("name" => "Madagascar","code" => "MG","alpha_3" => "MDG"),
            array("name" => "Malawi","code" => "MW","alpha_3" => "MWI"),
            array("name" => "Malaysia","code" => "MY","alpha_3" => "MYS"),
            array("name" => "Maldives","code" => "MV","alpha_3" => "MDV"),
            array("name" => "Mali","code" => "ML","alpha_3" => "MLI"),
            array("name" => "Malta","code" => "MT","alpha_3" => "MLT"),
            array("name" => "Marshall Islands","code" => "MH","alpha_3" => "MHL"),
            array("name" => "Martinique","code" => "MQ","alpha_3" => "MTQ"),
            array("name" => "Mauritania","code" => "MR","alpha_3" => "MRT"),
            array("name" => "Mauritius","code" => "MU","alpha_3" => "MUS"),
            array("name" => "Mayotte","code" => "YT","alpha_3" => "MYT"),
            array("name" => "Mexico","code" => "MX","alpha_3" => "MEX"),
            array("name" => "Micronesia, Federated States of","code" => "FM","alpha_3" => "FSM"),
            array("name" => "Moldova, Republic of","code" => "MD","alpha_3" => "MDA"),
            array("name" => "Monaco","code" => "MC","alpha_3" => "MCO"),
            array("name" => "Mongolia","code" => "MN","alpha_3" => "MNG"),
            array("name" => "Montenegro","code" => "ME","alpha_3" => "MNE"),
            array("name" => "Montserrat","code" => "MS","alpha_3" => "MSR"),
            array("name" => "Morocco","code" => "MA","alpha_3" => "MAR"),
            array("name" => "Mozambique","code" => "MZ","alpha_3" => "MOZ"),
            array("name" => "Myanmar","code" => "MM","alpha_3" => "MMR"),
            array("name" => "Namibia","code" => "NA","alpha_3" => "NAM"),
            array("name" => "Nauru","code" => "NR","alpha_3" => "NRU"),
            array("name" => "Nepal","code" => "NP","alpha_3" => "NPL"),
            array("name" => "Netherlands","code" => "NL","alpha_3" => "NLD"),
            array("name" => "Netherlands Antilles","code" => "AN","alpha_3" => "ANT"),
            array("name" => "New Caledonia","code" => "NC","alpha_3" => "NCL"),
            array("name" => "New Zealand","code" => "NZ","alpha_3" => "NZL"),
            array("name" => "Nicaragua","code" => "NI","alpha_3" => "NIC"),
            array("name" => "Niger","code" => "NE","alpha_3" => "NER"),
            array("name" => "Nigeria","code" => "NG","alpha_3" => "NGA"),
            array("name" => "Niue","code" => "NU","alpha_3" => "NIU"),
            array("name" => "Norfolk Island","code" => "NF","alpha_3" => "NFK"),
            array("name" => "Northern Mariana Islands","code" => "MP","alpha_3" => "MNP"),
            array("name" => "Norway","code" => "NO","alpha_3" => "NOR"),
            array("name" => "Oman","code" => "OM","alpha_3" => "OMN"),
            array("name" => "Pakistan","code" => "PK","alpha_3" => "PAK"),
            array("name" => "Palau","code" => "PW","alpha_3" => "PLW"),
            array("name" => "Palestinian Territory, Occupied","code" => "PS","alpha_3" => "PSE"),
            array("name" => "Panama","code" => "PA","alpha_3" => "PAN"),
            array("name" => "Papua New Guinea","code" => "PG","alpha_3" => "PNG"),
            array("name" => "Paraguay","code" => "PY","alpha_3" => "PRY"),
            array("name" => "Peru","code" => "PE","alpha_3" => "PER"),
            array("name" => "Philippines","code" => "PH","alpha_3" => "PHL"),
            array("name" => "Pitcairn","code" => "PN","alpha_3" => "PCN"),
            array("name" => "Poland","code" => "PL","alpha_3" => "POL"),
            array("name" => "Portugal","code" => "PT","alpha_3" => "PRT"),
            array("name" => "Puerto Rico","code" => "PR","alpha_3" => "PRI"),
            array("name" => "Qatar","code" => "QA","alpha_3" => "QAT"),
            array("name" => "Reunion","code" => "RE","alpha_3" => "REU"),
            array("name" => "Romania","code" => "RO","alpha_3" => "ROM"),
            array("name" => "Russian Federation","code" => "RU","alpha_3" => "RUS"),
            array("name" => "Rwanda","code" => "RW","alpha_3" => "RWA"),
            array("name" => "Saint Barthelemy","code" => "BL","alpha_3" => "BLM"),
            array("name" => "Saint Helena","code" => "SH","alpha_3" => "SHN"),
            array("name" => "Saint Kitts and Nevis","code" => "KN","alpha_3" => "KNA"),
            array("name" => "Saint Lucia","code" => "LC","alpha_3" => "LCA"),
            array("name" => "Saint Martin","code" => "MF","alpha_3" => "MAF"),
            array("name" => "Saint Pierre and Miquelon","code" => "PM","alpha_3" => "SPM"),
            array("name" => "Saint Vincent and the Grenadines","code" => "VC","alpha_3" => "VCT"),
            array("name" => "Samoa","code" => "WS","alpha_3" => "WSM"),
            array("name" => "San Marino","code" => "SM","alpha_3" => "SMR"),
            array("name" => "Sao Tome and Principe","code" => "ST","alpha_3" => "STP"),
            array("name" => "Saudi Arabia","code" => "SA","alpha_3" => "SAU"),
            array("name" => "Senegal","code" => "SN","alpha_3" => "SEN"),
            array("name" => "Serbia","code" => "RS","alpha_3" => "SRB"),
            array("name" => "Serbia and Montenegro","code" => "CS","alpha_3" => "SCG"),
            array("name" => "Seychelles","code" => "SC","alpha_3" => "SYC"),
            array("name" => "Sierra Leone","code" => "SL","alpha_3" => "SLE"),
            array("name" => "Singapore","code" => "SG","alpha_3" => "SGP"),
            array("name" => "St Martin","code" => "SX","alpha_3" => "SXM"),
            array("name" => "Slovakia","code" => "SK","alpha_3" => "SVK"),
            array("name" => "Slovenia","code" => "SI","alpha_3" => "SVN"),
            array("name" => "Solomon Islands","code" => "SB","alpha_3" => "SLB"),
            array("name" => "Somalia","code" => "SO","alpha_3" => "SOM"),
            array("name" => "South Africa","code" => "ZA","alpha_3" => "ZAF"),
            array("name" => "South Georgia and the South Sandwich Islands","code" => "GS","alpha_3" => "SGS"),
            array("name" => "South Sudan","code" => "SS","alpha_3" => "SSD"),
            array("name" => "Spain","code" => "ES","alpha_3" => "ESP"),
            array("name" => "Sri Lanka","code" => "LK","alpha_3" => "LKA"),
            array("name" => "Sudan","code" => "SD","alpha_3" => "SDN"),
            array("name" => "Suriname","code" => "SR","alpha_3" => "SUR"),
            array("name" => "Svalbard and Jan Mayen","code" => "SJ","alpha_3" => "SJM"),
            array("name" => "Swaziland","code" => "SZ","alpha_3" => "SWZ"),
            array("name" => "Sweden","code" => "SE","alpha_3" => "SWE"),
            array("name" => "Switzerland","code" => "CH","alpha_3" => "CHE"),
            array("name" => "Syrian Arab Republic","code" => "SY","alpha_3" => "SYR"),
            array("name" => "Taiwan, Province of China","code" => "TW","alpha_3" => "TWN"),
            array("name" => "Tajikistan","code" => "TJ","alpha_3" => "TJK"),
            array("name" => "Tanzania, United Republic of","code" => "TZ","alpha_3" => "TZA"),
            array("name" => "Thailand","code" => "TH","alpha_3" => "THA"),
            array("name" => "Timor-Leste","code" => "TL","alpha_3" => "TLS"),
            array("name" => "Togo","code" => "TG","alpha_3" => "TGO"),
            array("name" => "Tokelau","code" => "TK","alpha_3" => "TKL"),
            array("name" => "Tonga","code" => "TO","alpha_3" => "TON"),
            array("name" => "Trinidad and Tobago","code" => "TT","alpha_3" => "TTO"),
            array("name" => "Tunisia","code" => "TN","alpha_3" => "TUN"),
            array("name" => "Turkey","code" => "TR","alpha_3" => "TUR"),
            array("name" => "Turkmenistan","code" => "TM","alpha_3" => "TKM"),
            array("name" => "Turks and Caicos Islands","code" => "TC","alpha_3" => "TCA"),
            array("name" => "Tuvalu","code" => "TV","alpha_3" => "TUV"),
            array("name" => "Uganda","code" => "UG","alpha_3" => "UGA"),
            array("name" => "Ukraine","code" => "UA","alpha_3" => "UKR"),
            array("name" => "United Arab Emirates","code" => "AE","alpha_3" => "ARE"),
            array("name" => "United Kingdom","code" => "GB","alpha_3" => "GBR"),
            array("name" => "United States","code" => "US","alpha_3" => "USA"),
            array("name" => "United States Minor Outlying Islands","code" => "UM","alpha_3" => "UMI"),
            array("name" => "Uruguay","code" => "UY","alpha_3" => "URY"),
            array("name" => "Uzbekistan","code" => "UZ","alpha_3" => "UZB"),
            array("name" => "Vanuatu","code" => "VU","alpha_3" => "VUT"),
            array("name" => "Venezuela","code" => "VE","alpha_3" => "VEN"),
            array("name" => "Viet Nam","code" => "VN","alpha_3" => "VNM"),
            array("name" => "Virgin Islands, British","code" => "VG","alpha_3" => "VGB"),
            array("name" => "Virgin Islands, U.s.","code" => "VI","alpha_3" => "VIR"),
            array("name" => "Wallis and Futuna","code" => "WF","alpha_3" => "WLF"),
            array("name" => "Western Sahara","code" => "EH","alpha_3" => "ESH"),
            array("name" => "Yemen","code" => "YE","alpha_3" => "YEM"),
            array("name" => "Zambia","code" => "ZM","alpha_3" => "ZMB"),
            array("name" => "Zimbabwe","code" => "ZW","alpha_3" => "ZWE")
        );

        foreach ($country_list  as $item){
            $country = new Country();
            $country->name = $item['name'];
            $country->code = $item['code'];
            $country->alpha_3 = $item['alpha_3'];
            $country->save();
            unset($country);
        }
    }
}
